# Cursor settings
cursor_shape beam
cursor_blink_interval 0.5
cursor_blinking yes
cursor_animation yes
cursor_trail 150
cursor_trail_decay 0.06 0.4
cursor_trail_start_threshold 1
cursor_beam_thickness 2.0

allow_remote_control yes

# Bell / notification settings
enable_audio_bell no
window_alert_on_bell yes


# BEGIN_KITTY_THEME
# zenwritten_dark
include current-theme.conf
# END_KITTY_THEME

# --- New windows/panes in same directory ---
map ctrl+shift+enter launch --cwd=current         # new window
map cmd+enter launch --cwd=current
map ctrl+shift+right launch --cwd=current --location=hsplit  # horizontal split
map ctrl+shift+down  launch --cwd=current --location=vsplit  # vertical split

# --- Resize panes with arrow keys ---
map ctrl+shift+right  resize_window narrower
map ctrl+shift+left resize_window wider
map ctrl+shift+up    resize_window taller
map ctrl+shift+down  resize_window shorter
